# set the name for the project
name: lab03

services:
  hostA:
    image: netsos/rhit-netsec:latest
    container_name: client
    hostname: client
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      subnet1:
        ipv4_address: 10.10.0.4
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      echo '10.10.1.5 server' | sudo tee -a /etc/hosts > /dev/null &&
      sudo ip route change default dev eth0 via 10.10.0.10 &&
      tail -f /dev/null
      "

  # echo "10.10.0.4 client" | sudo tee /etc/hosts &&

  server:
    image: netsos/rhit-netsec:latest
    container_name: server
    hostname: server
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      subnet2:
        ipv4_address: 10.10.1.5
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      sudo bash /volumes/setup_telnetd.sh &&
      echo '10.10.0.4 client' | sudo tee -a /etc/hosts > /dev/null &&
      sudo ip route change default dev eth0 via 10.10.1.10 &&
      tail -f /dev/null
      "

  attacker:
    image: netsos/rhit-netsec:latest
    container_name: attacker
    hostname: attacker
    working_dir: /volumes/
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      subnet1:
        ipv4_address: 10.10.0.10
      subnet2:
        ipv4_address: 10.10.1.10
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

networks:
  subnet1:
    name: subnet1
    ipam:
      config:
        - subnet: 10.10.0.0/24
  subnet2:
    name: subnet2
    ipam:
      config:
        - subnet: 10.10.1.0/24
